spring:
  application:
    name: network-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.193.54.143:15133/focs
    username: focs
    password: Ejskdms!23
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
  web:
    resources:
      # http://localhost:8080/ase256/AESIv 이렇게 URI 로 접근 시
      # /Users/ijong-ug/IdeaProjects/network-client/src/main/resources/static/aes256/AESIv 에 접근 가능함
      static-locations: classpath:/static/
server:
  port: 8080
  servlet:
    context-path: /

